### ISSUE TITLE
Enable Github Discussions

### ISSUE THREAD

**Issue by stevefloyd** [Flockingbird/roost#49]
## Summary

Enable Github discussions to facilitate more lucid conversation around the project (without cluttering up the repo). 

## Motivation

I would like to ask some questions about the specification and roadmap as well as other random things that don't fit into a structured task or RFC. Currently, there isn't really anywhere to put that kind of stuff, and Github Discussions would be ideal for it. 

Those early discussions could end up answering a lot of other people's questions later on in the development (which saves time).

---
Footnotes and references

---
Please see the [Github Discussion Documentation](https://docs.github.com/en/discussions/collaborating-with-your-community-using-discussions/about-discussions)

**Comment by berkes** [comment]
Thanks! I'm not familiar with Github discussions, so I cannot foresee the exact niches or cases it covers.

If it is purely for chat, would a gitter or matrix room work as well? The latter would have preference as it is open, free and decentralized.
If it is more a forum, I'd gladly enable it until we have time and need to move to a (self)hosted forum. But in that case, we could also consider hosting such discussion on a (edit: existing, public) lemmy-instance. That way it would support development of lemmy (by using it) and be part of the fediverse. (Edit:): Or we could ask the folks at https://socialhub.activitypub.rocks/ for a room there?

Both obviously with links in the README and on the website.

I'm not against enabling the discussion feature, at all! Just that there might be alternatives for what we want, that align better with our own goals. But if those alternative don't cut it, or have severe downsides, we can document that here and move to GH discussions. 

What do you think?

**Comment by stevefloyd** [comment]
When a project is new and still collecting feedback and testing, having those early discussions in the actual repo - and the added searchability / findability that comes with structured discussions - is beneficial IMO.

So you do a Matrix or Telegram group... now how do people find those early discussions? Search through a never ending feed with years of updates? That’s not really good usability for new people. 

A Flarum or Discourse server would be a close second, but nothing would be as easy as simply clicking the “enable discussions” in the repo settings.

I would add to that - you could just do both. Enable the discussions feature in the repo UNTIL you have adequate time to setup a dedicated forum, then close discussions and direct people there.

**Comment by berkes** [comment]
👍🏿 https://github.com/Flockingbird/roost/discussions/51 🥳 

Thanks for taking the time to explain how it would benefit us.

I'm sorry if it sounded dismissive. On re-reading, I feel it may have sounded that way. I was merely trying to understand the benefits, as I am not familiar with GH discussions.

I'm especially excited about this feature: 

> You can **convert issues to discussions** either individually or bulk by labels. Looking at you, issues labeled “question” or “discussion”.

And the reverse:

> Declutter your issues by driving community content to where they belong in Discussions.

**Comment by berkes** [comment]
👍🏿 https://github.com/Flockingbird/roost/discussions/51 🥳 

Thanks for taking the time to explain how it would benefit us.

I'm sorry if it sounded dismissive. On re-reading, I feel it may have sounded that way. I was merely trying to understand the benefits, as I am not familiar with GH discussions.

I'm especially excited about this feature: 

> You can **convert issues to discussions** either individually or bulk by labels. Looking at you, issues labeled “question” or “discussion”.

And the reverse:

> Declutter your issues by driving community content to where they belong in Discussions.
