### ISSUE TITLE
Cannot comment in discussions...

### ISSUE THREAD

**Issue by stevefloyd** [Flockingbird/roost#52]
I attempted to comment in the welcome thread and received this message both times I tried to post FYI. You may have some permissions to tick off in order to allow people to post.

![image](https://user-images.githubusercontent.com/2344408/110984891-59504100-8331-11eb-8ac6-1050f40cb070.png)

**Comment by stevefloyd** [comment]
Looks like it just went through, disregard!

**Comment by berkes** [comment]
Yea. I had the same. 

I presume it is related to some degraded performance incident in GH actions and issues: https://www.githubstatus.com/incidents/wdhkj70kynwk
